default_config:

logger:
  default: warning
  logs:
      custom_components.renson_smartliving: info
      # custom_components.renson_smartliving.http: debug
      # custom_components.renson_smartliving.ws: debug
